<?
$PERM["suppliers_cabinet"]["*"]="D";
$PERM["suppliers_cabinet"]["15"]="X";
$PERM["desktop_app"]["*"]="D";
$PERM["local"]["7"]="W";
$PERM["about"]["8"]="W";
$PERM["personal"]["8"]="W";
$PERM["news"]["8"]="W";
$PERM["catalog"]["8"]="W";
$PERM["/"]["*"]="R";
?>