<?
use Bitrix\Main\Loader;
use Bitrix\Main\Config\Option;
use Bitrix\Main\Localization\Loc;
use Bitrix\Main\Application;

require ($_SERVER['DOCUMENT_ROOT'] . '/bitrix/header.php');
$APPLICATION->SetTitle( Loc::getMessage('ORDERS_MAKE_ORDER') );
$APPLICATION->SetPageProperty('title_prefix', '<span class="font-weight-semibold">'. Loc::getMessage("ORDERS_ORDERS") .'</span> - ');

?>

<?php
if(!Loader::includeModule('sotbit.b2bcabinet'))
{
    header('Location: '.SITE_DIR.'b2bcabinet/');
    exit;
}
?>
<?$APPLICATION->IncludeComponent(
  "bitrix:news.detail",
  "main_promo",
  Array(
    "ACTIVE_DATE_FORMAT" => "d.m.Y",
    "ADD_ELEMENT_CHAIN" => "N",
    "ADD_SECTIONS_CHAIN" => "N",
    "AJAX_MODE" => "N",
    "AJAX_OPTION_ADDITIONAL" => "",
    "AJAX_OPTION_HISTORY" => "N",
    "AJAX_OPTION_JUMP" => "N",
    "AJAX_OPTION_STYLE" => "Y",
    "BROWSER_TITLE" => "-",
    "CACHE_GROUPS" => "Y",
    "CACHE_TIME" => "36000000",
    "CACHE_TYPE" => "A",
    "CHECK_DATES" => "Y",
    "COMPOSITE_FRAME_MODE" => "A",
    "COMPOSITE_FRAME_TYPE" => "AUTO",
    "DETAIL_URL" => "",
    "DISPLAY_BOTTOM_PAGER" => "Y",
    "DISPLAY_DATE" => "Y",
    "DISPLAY_NAME" => "Y",
    "DISPLAY_PICTURE" => "Y",
    "DISPLAY_PREVIEW_TEXT" => "Y",
    "DISPLAY_TOP_PAGER" => "N",
    "ELEMENT_CODE" => "oformlenie-zakaza",
    "ELEMENT_ID" => "",
    "FIELD_CODE" => array("", ""),
    "IBLOCK_ID" => "28",
    "IBLOCK_TYPE" => "sotbit_origami_content",
    "IBLOCK_URL" => "",
    "INCLUDE_IBLOCK_INTO_CHAIN" => "N",
    "MESSAGE_404" => "",
    "META_DESCRIPTION" => "-",
    "META_KEYWORDS" => "-",
    "PAGER_BASE_LINK_ENABLE" => "N",
    "PAGER_SHOW_ALL" => "N",
    "PAGER_TEMPLATE" => ".default",
    "PAGER_TITLE" => "Страница",
    "PROPERTY_CODE" => array("", "FILE", ""),
    "SET_BROWSER_TITLE" => "N",
    "SET_CANONICAL_URL" => "N",
    "SET_LAST_MODIFIED" => "N",
    "SET_META_DESCRIPTION" => "N",
    "SET_META_KEYWORDS" => "N",
    "SET_STATUS_404" => "N",
    "SET_TITLE" => "N",
    "SHOW_404" => "N",
    "STRICT_SECTION_CHECK" => "N",
    "USE_PERMISSIONS" => "N",
    "USE_SHARE" => "N"
  )
);?>
<?$request = Application::getInstance()->getContext()->getRequest();

$APPLICATION->IncludeComponent(
    "bitrix:sale.order.ajax",
    "sotbit_order_make_simple",
    array(
        "PAY_FROM_ACCOUNT" => "Y",
        "COUNT_DELIVERY_TAX" => "N",
        "COUNT_DISCOUNT_4_ALL_QUANTITY" => "N",
        "ONLY_FULL_PAY_FROM_ACCOUNT" => "N",
        "ALLOW_AUTO_REGISTER" => "Y",
        "SEND_NEW_USER_NOTIFY" => "Y",
        "DELIVERY_NO_AJAX" => "Y",
        "TEMPLATE_LOCATION" => "popup",
        "PROP_1" => "",
        "PATH_TO_BASKET" => SITE_DIR."personal/cart/",
        "PATH_TO_PERSONAL" => "/b2bcabinet/",
        "PATH_TO_PAYMENT" => SITE_DIR."personal/order/payment/",
        "PATH_TO_ORDER" => SITE_DIR."personal/order/make/",
        "SET_TITLE" => "Y",
        "SHOW_ACCOUNT_NUMBER" => "Y",
        "DELIVERY_NO_SESSION" => "N",
        "COMPATIBLE_MODE" => "Y",
        "BASKET_POSITION" => "before",
        "BASKET_IMAGES_SCALING" => "adaptive",
        "SERVICES_IMAGES_SCALING" => "adaptive",
        "USER_CONSENT" => "Y",
        "USER_CONSENT_ID" => "1",
        "USER_CONSENT_IS_CHECKED" => "Y",
        "USER_CONSENT_IS_LOADED" => "Y",
        "ALLOW_APPEND_ORDER" => "Y",
        "SHOW_NOT_CALCULATED_DELIVERIES" => "L",
        "SPOT_LOCATION_BY_GEOIP" => "Y",
        "DELIVERY_TO_PAYSYSTEM" => "d2p",
        "SHOW_VAT_PRICE" => "Y",
        "USE_PREPAYMENT" => "N",
        "USE_PRELOAD" => "N",
        "ALLOW_USER_PROFILES" => "Y",
        "ALLOW_NEW_PROFILE" => "Y",
        "SHOW_PAYMENT_SERVICES_NAMES" => "Y",
        "SHOW_STORES_IMAGES" => "Y",
        "TEMPLATE_THEME" => "site",
        "SHOW_ORDER_BUTTON" => "final_step",
        "SHOW_TOTAL_ORDER_BUTTON" => "N",
        "SHOW_PAY_SYSTEM_LIST_NAMES" => "Y",
        "SHOW_PAY_SYSTEM_INFO_NAME" => "Y",
        "SHOW_DELIVERY_LIST_NAMES" => "Y",
        "SHOW_DELIVERY_INFO_NAME" => "Y",
        "SHOW_DELIVERY_PARENT_NAMES" => "Y",
        "SKIP_USELESS_BLOCK" => "Y",
        "SHOW_BASKET_HEADERS" => "N",
        "DELIVERY_FADE_EXTRA_SERVICES" => "N",
        "SHOW_COUPONS_BASKET" => "Y",
        "SHOW_COUPONS_DELIVERY" => "Y",
        "SHOW_COUPONS_PAY_SYSTEM" => "Y",
        "SHOW_NEAREST_PICKUP" => "N",
        "DELIVERIES_PER_PAGE" => "9",
        "PAY_SYSTEMS_PER_PAGE" => "9",
        "PICKUPS_PER_PAGE" => "5",
        "SHOW_PICKUP_MAP" => "Y",
        "SHOW_MAP_IN_PROPS" => "N",
        "PICKUP_MAP_TYPE" => "yandex",
        "PROPS_FADE_LIST_1" => "",
        "PROPS_FADE_LIST_2" => "",
        "ACTION_VARIABLE" => "soa-action",
        "PATH_TO_AUTH" => SITE_DIR."auth/",
        "DISABLE_BASKET_REDIRECT" => "N",
        "USE_PHONE_NORMALIZATION" => "Y",
        "PRODUCT_COLUMNS_VISIBLE" => array(
            0 => "PREVIEW_PICTURE",
            1 => "PROPS",
            2 => "DISCOUNT_PRICE_PERCENT_FORMATED",
            3 => "PRICE_FORMATED",
        ),
        "ADDITIONAL_PICT_PROP_2" => "-",
        "ADDITIONAL_PICT_PROP_3" => "-",
        "ADDITIONAL_PICT_PROP_8" => "-",
        "ADDITIONAL_PICT_PROP_9" => "-",
        "ADDITIONAL_PICT_PROP_19" => "-",
        "ADDITIONAL_PICT_PROP_20" => "-",
        "PRODUCT_COLUMNS_HIDDEN" => "",
        "COMPOSITE_FRAME_MODE" => "A",
        "COMPOSITE_FRAME_TYPE" => "AUTO",
        "USE_YM_GOALS" => "N",
        "USE_ENHANCED_ECOMMERCE" => "N",
        "USE_CUSTOM_MAIN_MESSAGES" => "N",
        "USE_CUSTOM_ADDITIONAL_MESSAGES" => "N",
        "USE_CUSTOM_ERROR_MESSAGES" => "N",
        "EMPTY_BASKET_HINT_PATH" => SITE_DIR,
        "HIDE_ORDER_DESCRIPTION" => "N",
        "ADDITIONAL_PICT_PROP_5" => "-",
        "ADDITIONAL_PICT_PROP_23" => "-",
        "ADDITIONAL_PICT_PROP_24" => "-",
        "COMPONENT_TEMPLATE" => "sotbit_order_make_simple",
        "ADDITIONAL_PICT_PROP_12" => "-",
        "ADDITIONAL_PICT_PROP_15" => "-",
        "ADDITIONAL_PICT_PROP_17" => "-",
        "ADDITIONAL_PICT_PROP_21" => "-",
        "ADDITIONAL_PICT_PROP_22" => "-"
    ),
    false
);?>

<?require ($_SERVER['DOCUMENT_ROOT'] . '/bitrix/footer.php');?>